name: Run NBA ETL Notebook

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download openmirroring_operations.py
        run: |
          curl -O https://raw.githubusercontent.com/microsoft/fabric-toolbox/main/tools/OpenMirroringPythonSDK/openmirroring_operations.py

      - name: Run notebook with Papermill
        run: |
          papermill notebooks/ingest_nba_stats.ipynb notebooks/output.ipynb
        env:
          FABRIC_CLIENT_ID: ${{ secrets.FABRIC_CLIENT_ID }}
          FABRIC_TENANT_ID: ${{ secrets.FABRIC_TENANT_ID }}
          FABRIC_CLIENT_SECRET: ${{ secrets.FABRIC_CLIENT_SECRET }}
