// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table nba_injury_reports_raw (GameDate:string, GameTime:string, Matchup:string, Team:string, PlayerName:string, CurrentStatus:string, Reason:string, EventProcessedUtcTime:datetime, PartitionId:long, EventEnqueuedUtcTime:datetime) 
.create-or-alter materialized-view with (Lookback = time(7.00:00:00), lookback_column = "EventEnqueuedUtcTime")  nba_injury_reports_latest on table nba_injury_reports_raw { nba_injury_reports_raw
  | summarize arg_max(EventEnqueuedUtcTime, *) by PlayerName, GameDate }
