name: Generate LeBron Game Log

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t gamelog-runner .

      - name: Run container
        run: docker run --rm -v ${{ github.workspace }}:/app gamelog-runner

      - name: Commit CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add lebron_2024_25_gamelog.csv
          git diff --cached --quiet || git commit -m "Update LeBron game log"
          git push
